apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavita
  namespace: kavita
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kavita
  template:
    metadata:
      labels:
        app: kavita
    spec:
      containers:
      - name: kavita
        image: jvmilazz0/kavita:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
            ephemeral-storage: "1Gi"
          limits:
            cpu: "1"
            memory: "1Gi"
            ephemeral-storage: "2Gi"
        env:
        - name: TZ
          value: "Asia/Kolkata"
        volumeMounts:
        - mountPath: /kavita/config
          name: config
        - mountPath: /manga
          name: library
        - mountPath: /shared
          name: shared-media
          readOnly: true
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: kavita-config
      - name: library
        persistentVolumeClaim:
          claimName: kavita-library
      - name: shared-media
        persistentVolumeClaim:
          claimName: kavita-shared-media
