apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-config
  namespace: kavita
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-library
  namespace: kavita
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
