apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openwebui
  namespace: openwebui
spec:
  ingressClassName: traefik
  rules:
  - host: openui.yashbhangale.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openwebui-open-webui
            port:
              number: 80
