apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  namespace: paperless
spec:
  limits:
  - type: Container
    default:
      cpu: "1"
      memory: "1Gi"
      ephemeral-storage: "2Gi"
    defaultRequest:
      cpu: "50m"
      memory: "128Mi"
      ephemeral-storage: "512Mi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-quota
  namespace: paperless
spec:
  hard:
    local-path.storageclass.storage.k8s.io/requests.storage: "40Gi"
    local-path.storageclass.storage.k8s.io/persistentvolumeclaims: "6"
