apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kasm-shared-media
  namespace: kasm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 35Gi
