apiVersion: v1
data:
  policy.csv: "# Admin user\ng, yash, role:admin\n\n# Read-only role permissions\np,
    role:readonly, applications, get, */*, allow\np, role:readonly, applicationsets,
    get, *, allow\np, role:readonly, logs, get, */*, allow\np, role:readonly, exec,
    get, */*, allow\np, role:readonly, projects, get, *, allow\np, role:readonly,
    repositories, get, *, allow\np, role:readonly, clusters, get, *, allow\n\n# Read-only
    user\ng, viewer, role:readonly  \n"
  policy.default: ""
  policy.matchMode: glob
  scopes: '[groups]'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2026-06-21T11:27:00Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.4.4
    helm.sh/chart: argo-cd-9.6.0
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "401598"
  uid: 044c8bcf-ff7e-4f00-93f9-0be700c300ee
