---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgB1FP8Lz2a+/BRi7CRYqQEtg2IBa/n9sGd5m+Ha9vHMg1U+uA55nqRpif6z7pBuBN1P7ewk4CdXuoQ554BnRuh/Cu4GjgSGjijS8+IZIFjPB5NzxH4tTAjD/6kL2elA4967bK8YUiiuC+Obsvmw5QdxR/APF2sYbQh1kAz3mrJCy4Bssrd82UHi7oV7LyBz4pVC/MRaz1io/1xEbI7MbCEkLi89UfdWdF7nIe3sQfLnEOW66wya5M72dryXLjcdiORKjtiBA9p6+nTlIxqcrgfTlPMbfAw/bnvrd/tiyh8FIW7qeey605bdDvbRIUX4rGaZ+g1iBmpMURleURYtUoQr7bu4S3HynwLbKucg+PoHO8fPm2PDfPJoYbnS1qDKJrVruCmJEHc/lsj32O/U/q6Bi8+MIRW+OF5f0dtaeS5E1xUGe5xihsQf7LuxALLeRhxE8hL8Kkr5Knmqnj27DjM86U2K2eFfeNX7ce9H9K6PizIaI0WVFvGnhtXKbw4YI5S/LOLHTdcMaIVG4YeChRN5YKt+we6mqeG0qIMf1O/zDPnL9akZt0mYQST2kfbSobtMWrDMd3dnI1KLCCj2fY/Lco/S+ChND9irbnOkxbMMTRCQ9IyN2FnttnhcHPNghoo15LWjazufTmoiLOuu69iAJz+gITZisjJLAXXDLEena5SPO7/5IaGZsnSYbJQ80hMHpGqlKXzpOUrRJArD+OQAyeaAO6k8NvaDE/ofzLFtcW2xgqzo2lLxAORMcljurwJbsGyFbQgvHd6+9zE2v4hDIoJ/b+hTsEkZLRrzduYuL1KXq7VXjJvB4V4oh7zQy0tmujL0P1ul2eGnSJs+R2CXAOG4alQLsGvZTIOjGPvvlDl05lAuEQMKESP2d5RBRgihgrKRd9IZshL5OcnNQlmedaCkb3iD53pTYrqiNEwc
  template:
    metadata:
      name: cloudflared-credentials
      namespace: cloudflared
